[package]
name = "flavors"
version = "0.1.0"
authors = ["Geoffroy Couprie <geo.couprie@gmail.com>"]

[dependencies]

[dependencies.nom]
version = "2.0"
features = ["verbose-errors"]

[features]
nightly = []
